export const EMPTY_FOLDER_COUNTS = { inbox: 0, starred: 0, snoozed: 0, drafts: 0 };

export const folders = [
  { id: 'inbox', label: 'Inbox', icon: 'inbox' },
  { id: 'starred', label: 'Starred', icon: 'star' },
  { id: 'snoozed', label: 'Snoozed', icon: 'clock' },
  { id: 'sent', label: 'Sent', icon: 'send' },
  { id: 'drafts', label: 'Drafts', icon: 'draft' },
];

export const UNIFIED_ACCOUNT = {
  id: '__unified__',
  name: 'All inboxes',
  email: 'Unified inbox',
  color: '#0b57d0',
  isUnified: true,
};

export const SMART_CATEGORIES = [
  { id: 'all', label: 'All mail', shortLabel: 'All', icon: 'inbox', description: 'Everything across every connected account (routine ops digests stay hidden)' },
  { id: 'primary', label: 'Primary', shortLabel: 'Primary', icon: 'person', description: 'People, conversations, and mail that needs attention' },
  { id: 'github_ci', label: 'GitHub CI', shortLabel: 'GitHub CI', icon: 'branch', description: 'Pull requests, checks, builds, and workflow runs' },
  { id: 'logs', label: 'Logs', shortLabel: 'Logs', icon: 'terminal', description: 'Automated logs, digests, and machine output' },
  { id: 'status', label: 'Status updates', shortLabel: 'Status', icon: 'activity', description: 'Incidents, uptime, deploys, and service health' },
  { id: 'ops_error', label: 'Ops errors', shortLabel: 'Ops errors', icon: 'alert', description: 'Failures from Workboard, Proxmox, Watchtower, and xer0/msl backups. Successful digests stay hidden.' },
];

export const PERSON_FLAGS = [
  { id: 'phil', label: 'Phil', shortLabel: 'Phil', emails: ['phil@midstatelitho.com', 'phil@midstaelitho.com'], color: '#0b57d0', description: 'Mail involving Phil at Midstate Litho' },
  { id: 'sarah', label: 'Sarah', shortLabel: 'Sarah', emails: ['sarah@midstatelitho.com'], color: '#c2185b', description: 'Mail involving Sarah at Midstate Litho' },
  { id: 'mark', label: 'Mark Culley', shortLabel: 'Mark', emails: ['mark_culley@sdmc.com'], color: '#00897b', description: 'Mail involving Mark Culley' },
  { id: 'support', label: 'Midstate Support', shortLabel: 'Support', emails: ['support@midstatelitho.com', 'support@midstaetlitho.com'], color: '#e8710a', description: 'Mail involving Midstate Litho support' },
  { id: 'sales', label: 'Midstate Sales', shortLabel: 'Sales', emails: ['sales@midstatelitho.com'], color: '#6c4fc7', description: 'Mail involving Midstate Litho sales' },
];

export const CATEGORY_ALIASES = {
  all: 'all',
  primary: 'primary',
  focused: 'primary',
  people: 'primary',
  github: 'github_ci',
  'github-ci': 'github_ci',
  github_ci: 'github_ci',
  ci: 'github_ci',
  builds: 'github_ci',
  log: 'logs',
  logs: 'logs',
  automated: 'logs',
  status: 'status',
  'status-update': 'status',
  status_updates: 'status',
  incidents: 'status',
  ops: 'ops_error',
  ops_error: 'ops_error',
  'ops-error': 'ops_error',
  ops_errors: 'ops_error',
  workboard: 'ops_error',
  proxmox: 'ops_error',
  watchtower: 'ops_error',
};

export const PROVIDER_PRESETS = {
  gmail: {
    id: 'gmail',
    label: 'Gmail',
    caption: 'Gmail or Google Workspace',
    mark: 'G',
    color: '#1a73e8',
    provider: 'gmail',
    imapHost: 'imap.gmail.com',
    imapPort: '993',
    smtpHost: 'smtp.gmail.com',
    smtpPort: '465',
    title: 'Connect Gmail securely',
    passwordTitle: 'Use a Google app password',
    passwordHint: 'Turn on 2-Step Verification, create a 16-digit app password, then paste it here. Your regular Google password will not work.',
    helpLabel: 'Google app-password help',
    helpUrl: 'https://support.google.com/accounts/answer/185833?hl=en',
  },
  icloud: {
    id: 'icloud',
    label: 'iCloud Mail',
    caption: 'Apple Account mail',
    mark: '☁',
    color: '#2589f5',
    provider: 'icloud',
    imapHost: 'imap.mail.me.com',
    imapPort: '993',
    smtpHost: 'smtp.mail.me.com',
    smtpPort: '587',
    title: 'Connect iCloud Mail',
    passwordTitle: 'Create an app-specific password',
    passwordHint: 'Your Apple Account needs two-factor authentication. Generate an app-specific password under Sign-In and Security, then paste it here.',
    helpLabel: 'Apple app-specific password help',
    helpUrl: 'https://support.apple.com/en-us/102654',
  },
  mailinabox: {
    id: 'mailinabox',
    label: 'Mail-in-a-Box',
    caption: 'Self-hosted mail server',
    mark: 'M',
    color: '#6c4fc7',
    provider: 'mailinabox',
    imapHost: 'box.xer5.com',
    imapPort: '993',
    smtpHost: 'box.xer5.com',
    smtpPort: '587',
    title: 'Connect Mail-in-a-Box',
    passwordTitle: 'Use the mailbox password',
    passwordHint: 'Use the full mailbox address and its Mail-in-a-Box mailbox password. GigaMail connects to box.xer5.com with IMAP TLS and SMTP STARTTLS.',
  },
  outlook: {
    id: 'outlook',
    label: 'Outlook',
    caption: 'Microsoft 365 or Outlook.com',
    mark: 'O',
    color: '#0078d4',
    provider: 'outlook',
    imapHost: 'outlook.office365.com',
    imapPort: '993',
    smtpHost: 'smtp.office365.com',
    smtpPort: '587',
    title: 'Connect Outlook',
    passwordTitle: 'Use an app password if your account supports one',
    passwordHint: 'Microsoft may require OAuth or an organization-approved app password. Basic mailbox passwords are often blocked by tenant policy.',
  },
  custom: {
    id: 'custom',
    label: 'Other IMAP',
    caption: 'Any IMAP + SMTP provider',
    mark: '@',
    color: '#4f636f',
    provider: 'custom',
    imapHost: '',
    imapPort: '993',
    smtpHost: '',
    smtpPort: '465',
    title: 'Connect another provider',
    passwordTitle: 'Use a provider app password when available',
    passwordHint: 'Enter the encrypted IMAP and SMTP settings from your provider. A dedicated app password is safer than your primary sign-in password.',
  },
};
