import { normalizeThread } from './normalize.js';

export const demoAccounts = [
  {
    id: 'me',
    name: 'Sam Rivera',
    email: 'sam@rivera.example',
    color: '#8e24aa',
    signature: '<div><strong style="color:#202124">Sam Rivera</strong><br><span style="color:#5f6368">Rivera Labs</span><br><a href="https://rivera.example">rivera.example</a></div>',
    connected: true,
  },
  {
    id: 'studio',
    name: 'Rivera Studio',
    email: 'hello@riverastudio.example',
    color: '#0b57d0',
    signature: 'Best,\nRivera Studio',
    connected: true,
  },
  {
    id: 'personal',
    name: 'Personal',
    email: 'sam.personal@example.com',
    color: '#e8710a',
    connected: true,
  },
];

const demoThreads = [
  {
    id: 'design-sync',
    threadId: 'design-sync',
    subject: 'Design sync — final notes',
    snippet: 'I have added the final interaction notes and the handoff links for tomorrow.',
    from: { name: 'Maya Chen', email: 'maya@studio.com', color: '#0b57d0' },
    participants: ['Maya Chen', 'You', 'Jordan Lee'],
    timestamp: new Date(Date.now() - 1000 * 60 * 17).toISOString(),
    unread: true,
    starred: true,
    labels: ['Work'],
    folder: 'inbox',
    messageCount: 3,
    messages: [
      {
        id: 'design-sync-1',
        from: { name: 'Maya Chen', email: 'maya@studio.com', color: '#0b57d0' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
        body: 'Hi Sam,\n\nI have added the final interaction notes and the handoff links for tomorrow. The desktop flow is ready for one last pass.\n\nMaya',
        remoteContentBlocked: true,
      },
      {
        id: 'design-sync-2',
        from: { name: 'Sam Rivera', email: 'sam@rivera.example', color: '#8e24aa' },
        to: ['Maya Chen', 'Jordan Lee'],
        timestamp: new Date(Date.now() - 1000 * 60 * 41).toISOString(),
        body: 'Looks excellent. I left two small comments in the prototype and will review the responsive states before the sync.\n\nThanks!',
      },
      {
        id: 'design-sync-3',
        from: { name: 'Maya Chen', email: 'maya@studio.com', color: '#0b57d0' },
        to: ['Sam Rivera', 'Jordan Lee'],
        timestamp: new Date(Date.now() - 1000 * 60 * 17).toISOString(),
        body: 'Perfect — I will bring the updated mobile behavior to the meeting too. See you tomorrow.',
      },
    ],
  },
  {
    id: 'infrastructure',
    threadId: 'infrastructure',
    subject: 'aMail infrastructure proposal',
    snippet: 'The isolated Docker deployment is ready for review, with no host port collisions.',
    from: { name: 'Avery Thompson', email: 'avery@ops.example', color: '#00897b' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    unread: true,
    starred: false,
    labels: ['Important'],
    folder: 'inbox',
    messageCount: 1,
    messages: [
      {
        id: 'infrastructure-1',
        from: { name: 'Avery Thompson', email: 'avery@ops.example', color: '#00897b' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        body: 'Hi Sam,\n\nThe isolated Docker deployment is ready for review. It uses its own named volumes and a dedicated network, so it will not conflict with any existing services on the host.\n\nAvery',
      },
    ],
  },
  {
    id: 'github-ci',
    threadId: 'github-ci',
    subject: '[aMail] CI failed on main (#842)',
    snippet: 'The test job failed after 2m 18s in message-html.test.js. View the workflow run for annotations.',
    from: { name: 'GitHub Actions', email: 'notifications@github.com', color: '#24292f' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2.6).toISOString(),
    unread: true,
    starred: false,
    labels: ['GitHub', 'CI'],
    folder: 'inbox',
    messageCount: 1,
    category: 'github_ci',
    categoryLabel: 'GitHub CI',
    categoryReason: 'Matched a GitHub Actions workflow notification.',
    messages: [
      {
        id: 'github-ci-1',
        from: { name: 'GitHub Actions', email: 'notifications@github.com', color: '#24292f' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2.6).toISOString(),
        body: 'Workflow: CI\nBranch: main\nCommit: 5ab1c72\n\nThe test job failed after 2m 18s in message-html.test.js. View the workflow run for annotations.',
      },
    ],
  },
  {
    id: 'service-status',
    threadId: 'service-status',
    subject: 'Resolved: Elevated API latency',
    snippet: 'All systems have recovered. We will publish a full incident review within two business days.',
    from: { name: 'Rivera Status', email: 'status@rivera.example', color: '#188038' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3.2).toISOString(),
    unread: false,
    starred: false,
    labels: ['Status'],
    folder: 'inbox',
    messageCount: 3,
    category: 'status',
    categoryLabel: 'Status update',
    categoryReason: 'Recognized a resolved service incident update.',
    messages: [
      {
        id: 'service-status-1',
        from: { name: 'Rivera Status', email: 'status@rivera.example', color: '#188038' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3.2).toISOString(),
        body: 'All systems have recovered. We will publish a full incident review within two business days.',
      },
    ],
  },
  {
    id: 'backup-log',
    threadId: 'backup-log',
    subject: 'Nightly backup completed with 3 warnings',
    snippet: 'Backup completed in 18m 42s. Three stale cache files were skipped and no mailbox data was lost.',
    from: { name: 'Mail Server Logs', email: 'logs@mail.rivera.example', color: '#5f6368' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3.7).toISOString(),
    unread: false,
    starred: false,
    labels: ['Logs'],
    folder: 'inbox',
    messageCount: 1,
    category: 'logs',
    categoryLabel: 'Log digest',
    categoryReason: 'Matched automated server log and backup language.',
    messages: [
      {
        id: 'backup-log-1',
        from: { name: 'Mail Server Logs', email: 'logs@mail.rivera.example', color: '#5f6368' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3.7).toISOString(),
        body: 'Backup completed in 18m 42s.\n\nWarnings: 3 stale cache files skipped.\nMailbox data lost: 0\nArchive verified: yes',
      },
    ],
  },
  {
    id: 'watchtower-ok',
    threadId: 'watchtower-ok',
    subject: 'Watchtower: all containers up to date',
    snippet: 'No container updates were required. This daily digest stays out of All mail unless something fails.',
    from: { name: 'Watchtower', email: 'watchtower@home.lab', color: '#455a64' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    unread: true,
    starred: false,
    labels: ['Ops'],
    folder: 'inbox',
    messageCount: 1,
    category: 'ops_quiet',
    categoryLabel: 'Ops digests',
    categoryReason: 'Routine watchtower digest with no error signal.',
    messages: [
      {
        id: 'watchtower-ok-1',
        from: { name: 'Watchtower', email: 'watchtower@home.lab', color: '#455a64' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        body: 'All containers are up to date. No action needed.',
      },
    ],
  },
  {
    id: 'proxmox-fail',
    threadId: 'proxmox-fail',
    subject: 'Proxmox backup failed on pve-1',
    snippet: 'vzdump finished with errors on VM 105. Review the task log before the next nightly run.',
    from: { name: 'Proxmox', email: 'root@proxmox.local', color: '#e53935' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString(),
    unread: true,
    starred: false,
    labels: ['Ops'],
    folder: 'inbox',
    messageCount: 1,
    category: 'ops_error',
    categoryLabel: 'Ops errors',
    categoryReason: 'Ops error from proxmox.',
    messages: [
      {
        id: 'proxmox-fail-1',
        from: { name: 'Proxmox', email: 'root@proxmox.local', color: '#e53935' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString(),
        body: 'TASK ERROR: vzdump failed for VM 105. Exit code 1.',
      },
    ],
  },
  {
    id: 'priya-note',
    threadId: 'priya-note',
    subject: 'Press schedule for Thursday',
    snippet: 'Can you confirm the afternoon press window for the Thursday print run?',
    from: { name: 'Priya', email: 'priya@printworks.example', color: '#0b57d0' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    unread: true,
    starred: false,
    labels: [],
    folder: 'inbox',
    messageCount: 1,
    category: 'primary',
    messages: [
      {
        id: 'priya-note-1',
        from: { name: 'Priya', email: 'priya@printworks.example', color: '#0b57d0' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
        body: 'Can you confirm the afternoon press window for the Thursday print run?',
      },
    ],
  },
  {
    id: 'receipt',
    threadId: 'receipt',
    subject: 'Your receipt from Figma',
    snippet: 'Thanks for your payment. Your monthly invoice is attached to this email.',
    from: { name: 'Figma', email: 'billing@figma.com', color: '#ef6c00' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    unread: false,
    starred: false,
    labels: ['Receipts'],
    folder: 'inbox',
    messageCount: 1,
    hasAttachments: true,
    messages: [
      {
        id: 'receipt-1',
        from: { name: 'Figma', email: 'billing@figma.com', color: '#ef6c00' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
        body: 'Thanks for your payment. Your monthly invoice is attached to this email.',
        attachments: [{ name: 'figma-invoice-july.pdf', size: '124 KB' }],
      },
    ],
  },
  {
    id: 'weekend',
    threadId: 'weekend',
    subject: 'A quiet place for the weekend',
    snippet: 'I found a small cabin that looks ideal — have a look when you get a minute.',
    from: { name: 'Jordan Lee', email: 'jordan@example.com', color: '#c2185b' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    unread: false,
    starred: true,
    labels: [],
    folder: 'inbox',
    messageCount: 2,
    messages: [
      {
        id: 'weekend-1',
        from: { name: 'Jordan Lee', email: 'jordan@example.com', color: '#c2185b' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
        body: 'I found a small cabin that looks ideal — have a look when you get a minute.',
      },
      {
        id: 'weekend-2',
        from: { name: 'Sam Rivera', email: 'sam@rivera.example', color: '#8e24aa' },
        to: ['Jordan Lee'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
        body: 'This looks wonderful. I am in — let’s check availability this evening.',
      },
    ],
  },
  {
    id: 'security',
    threadId: 'security',
    subject: 'New sign-in from Detroit, MI',
    snippet: 'A new device signed in to your account. If this was you, no action is needed.',
    from: { name: 'aMail Security', email: 'security@amail.local', color: '#455a64' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    unread: false,
    starred: false,
    labels: ['Security'],
    folder: 'inbox',
    messageCount: 1,
    messages: [
      {
        id: 'security-1',
        from: { name: 'aMail Security', email: 'security@amail.local', color: '#455a64' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
        body: 'A new device signed in to your account. If this was you, no action is needed.\n\nDevice: Firefox on macOS\nLocation: Detroit, MI',
      },
    ],
  },
  {
    id: 'newsletter',
    threadId: 'newsletter',
    subject: 'The Friday field notes',
    snippet: 'A few excellent reads, a small idea about tools, and a recipe worth keeping.',
    from: { name: 'Field Notes', email: 'hello@fieldnotes.news', color: '#7b1fa2' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    unread: false,
    starred: false,
    labels: ['Newsletters'],
    folder: 'inbox',
    messageCount: 1,
    messages: [
      {
        id: 'newsletter-1',
        from: { name: 'Field Notes', email: 'hello@fieldnotes.news', color: '#7b1fa2' },
        to: ['Sam Rivera'],
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
        body: 'A few excellent reads, a small idea about tools, and a recipe worth keeping.\n\nThis edition was delivered with remote images held back for your privacy.',
        remoteContentBlocked: true,
      },
    ],
  },
];

const demoDraftSources = [
  {
    id: 'draft:preview-press',
    draftId: 'preview-press',
    threadId: 'draft:preview-press',
    folder: 'drafts',
    subject: 'Re: Press schedule for Thursday',
    snippet: 'Thursday afternoon still works. I will send the confirmed window after I check the run sheet.',
    from: { name: 'Sam Rivera', email: 'sam@rivera.example', color: '#8e24aa' },
    to: [{ name: 'Priya', email: 'priya@printworks.example' }],
    timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    unread: false,
    starred: false,
    labels: ['Draft'],
    messageCount: 1,
    messages: [
      {
        id: 'draft-message:preview-press',
        from: { name: 'Sam Rivera', email: 'sam@rivera.example', color: '#8e24aa' },
        to: [{ name: 'Priya', email: 'priya@printworks.example' }],
        timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
        body: 'Hi Priya,\n\nThursday afternoon still works. I will send the confirmed window after I check the run sheet.\n\nSam',
        htmlBody: '<p>Hi Priya,</p><p>Thursday afternoon still works. I will send the confirmed window after I check the run sheet.</p><p>Sam</p>',
      },
    ],
  },
  {
    id: 'draft:preview-design',
    draftId: 'preview-design',
    threadId: 'draft:preview-design',
    folder: 'drafts',
    subject: 'Design sync follow-up',
    snippet: 'Thanks for the handoff notes. I left two comments on the mobile states and will send a cleaned reply shortly.',
    from: { name: 'Sam Rivera', email: 'sam@rivera.example', color: '#8e24aa' },
    to: [{ name: 'Maya Chen', email: 'maya@studio.com' }, { name: 'Jordan Lee', email: 'jordan@example.com' }],
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    unread: false,
    starred: false,
    labels: ['Draft'],
    messageCount: 1,
    messages: [
      {
        id: 'draft-message:preview-design',
        from: { name: 'Sam Rivera', email: 'sam@rivera.example', color: '#8e24aa' },
        to: [{ name: 'Maya Chen', email: 'maya@studio.com' }, { name: 'Jordan Lee', email: 'jordan@example.com' }],
        timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
        body: 'Hi Maya,\n\nThanks for the handoff notes. I left two comments on the mobile states and will send a cleaned reply shortly.\n\nSam',
        htmlBody: '<p>Hi Maya,</p><p>Thanks for the handoff notes. I left two comments on the mobile states and will send a cleaned reply shortly.</p><p>Sam</p>',
      },
    ],
  },
];

export const demoMailboxThreads = demoThreads.map(normalizeThread);
export const demoDraftThreads = demoDraftSources.map(normalizeThread);
